# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

run:
  allow-parallel-runners: true
  timeout: 90s

linters:
  disable-all: true
  enable:
    # Enabled
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - gci
    - gocheckcompilerdirectives
    - gocritic
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - makezero
    - mirror
    - musttag
    - nakedret
    - nolintlint
    - paralleltest
    - perfsprint
    - predeclared
    - reassign
    - staticcheck
    - tenv
    - testableexamples
    - tparallel
    - unconvert
    - usestdlibvars
    - whitespace

    - customlint

    # Need to add headers
    # - goheader

    # Check
    # - exhaustive
    # - gosec
    # - revive
    # - stylecheck
    # - unparam
    # - unused

linters-settings:
  custom:
    customlint:
      type: module

  wrapcheck:
    ignorePackageGlobs:
      - encoding/*
      - github.com/go-json-experiment/*

  gocritic:
    enabled-checks:
      - emptyFallthrough
    disabled-checks:
      - appendAssign
      - assignOp
      - commentFormatting
      - dupBranchBody
      - elseif
      - ifElseChain
      - singleCaseSwitch
      - valSwap

  staticcheck:
    checks:
      - '*'
      - '-SA9003'
      - '-SA1019' # TODO: reenable

#   revive:
#     enable-all-rules: true
#     rules:
#       - name: unused-parameter
#         disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude:
    - '^could not import'
    - '^: #'
    - 'imported and not used$'
